### ISSUE TITLE
How to use with mongodb?

### ISSUE THREAD

**Issue by xfg** [T-PWK/flake-idgen#2]
I generate `id` with `flake-idgen` and `biguint-format` but when try to save this id to mongodb get next error:

`Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters at new ObjectID`

Is it real fix?

**Comment by scragg0x** [comment]
@xfg from looking over the mongo docs.  The ObjectId appears to be in similar format except that the timestamp is in seconds and not ms. https://docs.mongodb.com/manual/reference/method/ObjectId/
