### ISSUE TITLE
Min and Max values ?

### ISSUE THREAD

**Issue by lester-s** [T-PWK/flake-idgen#3]
Hello,
I would like to know if the generated id converted in decimal stay inside the range of the  ?
[Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/enUS/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) ?

Thank you and have a nice day.

**Comment by scragg0x** [comment]
@lester-s no, the id is 64bit, each of which having some significance in it's current form.
