### ISSUE TITLE
Easiest way to get datacenter/worker id from generated id

### ISSUE THREAD

**Issue by Bramzor** [T-PWK/flake-idgen#9]
Maybe it's a good idea to add a get function for retrieving the datacenter or worker id from a generated id?

**Comment by gogomarine** [comment]
+1
Yeah, If something wrong, we can locate data center and worker immediately.

**Comment by vipermind** [comment]
As of version 1.3.0 a generator instance has a set of properties: `id`, `datacenter` and `worker` that can be used to see values used during creation.
